Make sragdoll unable to be used in pvp
CFC-Servers/cfc_ulx_commands pull request #118
Opened 2023-07-13 00:23 UTC by NullLikesNothing

simple check

2023-07-13 00:25 UTC, legokidlogan requested changes
Replace `ply` with `calling_ply`

2023-07-13 00:27 UTC, legokidlogan requested changes

2023-07-13 00:27 UTC, legokidlogan commented on lua/ulx/modules/sh/cfc_silent_ragdoll.lua
> +            ply:ChatPrint( "You cannot ragdoll or propify yourself in PvP mode!" )
```suggestion
        elseif calling_ply.IsInPvp and calling_ply:IsInPvp() then
            calling_ply:ChatPrint( "You cannot ragdoll or propify yourself in PvP mode!" )
```

2023-07-13 00:45 UTC, legokidlogan approved these changes

2023-07-20 17:47 UTC, plally requested changes

2023-07-20 17:47 UTC, plally commented on lua/ulx/modules/sh/cfc_silent_ragdoll.lua
> +            calling_ply:ChatPrint( "You cannot ragdoll or propify yourself in PvP mode!" )
```suggestion
            ULib.tsayError( calling_ply, "You cannot ragdoll or propify yourself in PvP mode!", true )
```

2023-07-21 20:05 UTC, brandonsturgeon approved these changes

2023-07-21 20:06 UTC, merged