Add timed pvp ban
CFC-Servers/cfc_ulx_commands pull request #47
Opened 2021-07-08 17:08 UTC by wrefgtzweve

2021-07-08 17:24 UTC, wrefgtzweve commented
![image](https://user-images.githubusercontent.com/69946827/124965195-20478500-e022-11eb-8ebe-6fcaf5b98b03.png)
Works as can be seen, the errors are because didn't have pac installed.

2021-07-09 20:37 UTC, brandonsturgeon approved these changes
This would be a great opportunity for moonscript classes, just sayin' 😏

2021-07-09 20:38 UTC, brandonsturgeon requested changes
Can we add some user feedback about the user being pvp banned?

2021-07-10 01:27 UTC, brandonsturgeon approved these changes

2021-07-10 01:27 UTC, merged