Add ulx decals and ulx sounds
CFC-Servers/cfc_ulx_commands pull request #99
Opened 2022-07-05 21:59 UTC by wrefgtzweve

2022-07-14 21:35 UTC, loganlearner requested changes

2022-07-14 21:35 UTC, loganlearner commented on lua/ulx/modules/sh/cfc_decals.lua
> +        net.Broadcast()
`net.Broadcast` already runs on all players, you'll need to take it out of that loop 😬

2022-07-14 21:41 UTC, loganlearner approved these changes

2022-07-27 22:17 UTC, brandonsturgeon approved these changes

2022-07-27 22:17 UTC, merged